### ISSUE TITLE
Credit Inspiration?

### ISSUE THREAD

**Issue by zchrykng** [Nitrino/nil-ui#5]
Hi! I could be mistaken but from the name and look of this theme it would seem that it is designed to be a port of the [Nil theme](https://github.com/nilium/st2-nil-theme) for Sublime Text. If that is the case, I think it would be right to give credit and link to the theme that inspired this one.

**Comment by Nitrino** [comment]
Yes you are right. Add in READMI gratitude block
https://github.com/Nitrino/nil-ui#gratitude

**Comment by zchrykng** [comment]
Awesome! :+1:
